# 基础镜像
FROM ubuntu:20.04

# 我第一个dockerfile，代码到处抄的，哈哈哈

# 维护者信息
MAINTAINER eric <eric123456123456@163.com>

# 环境变量
ENV DEBIAN_FRONTEND=noninteractive \
    SIZE=1200x800 \
    PASSWD=123456 

USER root
WORKDIR /root

# 设定密码
# RUN echo "root:$PASSWD" | chpasswd

# 安装 换源
RUN cp /etc/apt/sources.list /etc/apt/sources.list.backup && \
    # sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list && \
    # sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get -y update && \
    # tools
    apt-get install -y vim nano git subversion wget curl net-tools locales bzip2 unzip iputils-ping traceroute firefox firefox-locale-zh-hans ttf-wqy-microhei gedit ibus-pinyin && \
    locale-gen en_US.UTF-8 

RUN curl -sLkO https://is.gd/nomachineMATE && \
    bash nomachineMATE

# 导出特定端口
EXPOSE 22 4000 4001 4002 4003 4004 4005 4006 4007 4008 4009


